### ISSUE TITLE
How i can install this script in regular server ? 

### ISSUE THREAD

**Issue by hypermax** [ryuzee/SlideHub#104]
Hello  

Can i install this script in a regular server with Cpanel  and My sql database  and how i can do that  

Thank you a lot for this great app

**Comment by ryuzee** [comment]
@hypermax 

You can install the app into any servers you want. However, running this app requires Amazon S3/Amazon SQS or Azure Blob Storage/Azure Blob Queue to store converted slide data and accumulate conversion task requests.

More detailed information about how to install the app can be seen in README. See https://github.com/ryuzee/SlideHub/blob/master/README.md
I'm willing to answer questions when you are following the instruction and having questions.

**Comment by hypermax** [comment]
Hi @ryuzee  There are no option to moderate the slides of others members ? like delete edit ... 

There are no dashboard for the website admin  ?

**Comment by ryuzee** [comment]
@hypermax There's admin panel. You can login to the admin panel with default admin account. (admin@example.com / passw0rd). After logged in, you need to change admin password or add admin privilege to your other account and remove admin account for the security.

CC: @cusanelly
