### ISSUE TITLE
Upload view Error

### ISSUE THREAD

**Issue by cusanelly** [ryuzee/SlideHub#112]
Hi Ryuzee.

I have another issue and i need your help.
Your updates on how to install your app works like a charm.

Now, i have this issue, when i login and head up to the upload option, on the menu dropdown, it just says:
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."
Link: http://ec2-52-44-77-247.compute-1.amazonaws.com/slides/new
I try to check  the log files, however, it just says error 500. Probably i'm seeing the wrong log?
(slidehub_error.log don't show anything, as equal error.log).
If you can give me a workaround to deal with this, i will truly appreciate it.

Hope to hear from you soon.

**Comment by ryuzee** [comment]
@cusanelly 

I've just tried to signup to your environment. However signup also failed.
From this, most doubtful thing is database connectivity.

If you are running the app as production mode (from error screen, it may be), you can find a log file named 'production.log'. In the 'production log', all queries and information were recorded.

**Comment by cusanelly** [comment]
Hi Ryuzee.
I was able to check production.log, and i have found the issue, wrong AWS region.
Thank you very much.
