### ISSUE TITLE
1 error prohibited this slide from being saved. Key can't be blank

### ISSUE THREAD

**Issue by cusanelly** [ryuzee/SlideHub#113]
Hi Ryuzee.

Now, i having this issue under the slide/new section at the time i try to upload the file.

1 error prohibited this slide from being saved:
Key can't be blank

I have check the form, after i filled all the form fields, Create Slide button shows disable. However, i force the button to be enable and that's the error that shows after i click it.
Input field is not generating the key. It is being generated like this:  
name="slide[key]"

No key, so, hope i receive your opinion about this issue and what i have to do to solve it.
Thank you very much.

**Comment by ryuzee** [comment]
@cusanelly 

At the upload form, first thing to do is to select a pdf or ppt(x) file and then upload will start. 
When upload completes, "Save" button become to be enabled.
It means uploading your file to S3 was failed.
See app/views/slides/aws/_upload_js.erb

Check your S3 bucket name (you need to create 2 buckets in your region and specify these 2 bucket names to your environmental variable)
If you are using Google Chrome, run "Developer Tool" to confirm the console log.

**Comment by cusanelly** [comment]
Hi @ryuzee 

Yes, i have S3 bucket under the same region and setup buckets names under the env variables, however, by the time i create the IAM user, forgot to attach S3FullAccess policy to it.
After setup S3FullAccess policy to the IAM user, everything start working just fine.

Once again, thank you very much for your help and your time.
