### ISSUE TITLE
FATAL -- : ActionController::RoutingError (No route matches [GET] "/images/favicon.ico"):

### ISSUE THREAD

**Issue by cusanelly** [ryuzee/SlideHub#114]
Hi @ryuzee 
Please see image attached.
![message](https://cloud.githubusercontent.com/assets/697140/18817625/568c2c84-8333-11e6-94c5-218827bfbff8.jpg)

I'm getting this message after I upload either a .pdf or a .pptx file.
On production.log file appears this message:

(Debug and Info messages) -------------------------------

I, [2016-09-26T03:41:16.186955 #1350] INFO -- : Started GET "/slides/index" for 66.249.93.211 at 2016-09-26 03:41:16 +0900 
I, [2016-09-26T03:41:16.187843 #1350] INFO -- : Processing by SlidesController#index as HTML 
D, [2016-09-26T03:41:16.189898 #1350] DEBUG -- :^[[1m^[[35mSlide Load (0.1ms)^[[0m SELECT `slides`.* FROM `slides` WHERE (convert_status = 100) ORDER BY total_view desc LIMIT 8 
I, [2016-09-26T03:41:16.190051 #1350] INFO -- : Rendered slides/_thumbnail_template.html.erb (0.6ms) 
D, [2016-09-26T03:41:16.190558 #1350] DEBUG -- :^[[1m^[[36mSlide Load (0.1ms)^[[0m ^[[1mSELECT `slides`.* FROM `slides` WHERE (convert_status = 100) ORDER BY created_at desc LIMIT 8^[[0m 
I, [2016-09-26T03:41:16.190690 #1350] INFO -- : Rendered slides/_thumbnail_template.html.erb (0.3ms) 
I, [2016-09-26T03:41:16.190755 #1350] INFO -- :Rendered slides/index.html.erb within layouts/application (1.6ms)
D, [2016-09-26T03:41:16.193360 #1350] DEBUG -- : ^[[1m^[[35mCategory Load(0.1ms)^[[0m SELECT `categories`.* FROM `categories` ORDER BY id asc 
D, [2016-09-26T03:41:16.194598 #1350] DEBUG -- : ^[[1m^[[36mUser Load(0.1ms)^[[0m ^[[1mSELECT `users`.* FROM `users` WHERE `users`.`id` = 2 ORDER BY `users`.`id` ASC LIMIT 1^[[0m 
I, [2016-09-26T03:41:16.196246 #1350] INFO -- : Completed 200 OK in 8ms (Views: 6.9ms | ActiveRecord: 0.4ms) 
I, [2016-09-26T03:43:01.909340 #1353] INFO -- : Started GET "/" for190.75.118.58 at 2016-09-26 03:43:01 +0900 
I, [2016-09-26T03:43:01.910069 #1353] INFO -- : Processing by SlidesController#index as HTML 
D, [2016-09-26T03:43:01.911954 #1353] DEBUG -- : ^[[1m^[[35mSlide Load (0.1ms)^[[0m SELECT `slides`.* FROM `slides` WHERE (convert_status = 100) ORDER BY total_view desc LIMIT 8 
I, [2016-09-26T03:43:01.912100 #1353] INFO -- : Rendered slides/_thumbnail_template.html.erb (0.7ms) 
D, [2016-09-26T03:43:01.912714 #1353] DEBUG -- : ^[[1m^[[36mSlide Load (0.1ms)^[[0m ^[[1mSELECT `slides`.* FROM `slides` WHERE (convert_status = 100)ORDER BY created_at desc LIMIT 8^[[0m 
I, [2016-09-26T03:43:01.912960 #1353] INFO -- : Rendered slides/_thumbnail_template.html.erb (0.4ms) 
I, [2016-09-26T03:43:01.913052 #1353] INFO -- : Rendered slides/index.html.erb within layouts/application (1.9ms) 
D, [2016-09-26T03:43:01.915641 #1353] DEBUG -- : ^[[1m^[[35mCategory Load (0.1ms)^[[0m SELECT `categories`.* FROM `categories` ORDER BY id asc 
I, [2016-09-26T03:43:01.917288 #1353] INFO -- : Completed 200 OK in 7ms (Views: 6.1ms | ActiveRecord: 0.3ms) 
I, [2016-09-26T03:43:03.684106 #1350] INFO -- : Started GET "/images/favicon.ico"for 190.75.118.58 at 2016-09-26 03:43:03 +0900

(Error Message) ------------------------------------

F, [2016-09-26T03:43:03.685328 #1350] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/images/favicon.ico"):
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  unicorn (5.0.1) lib/unicorn/http_server.rb:562:in `process_client'
  unicorn (5.0.1) lib/unicorn/http_server.rb:658:in `worker_loop'
  unicorn (5.0.1) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  unicorn (5.0.1) lib/unicorn/http_server.rb:132:in `start'
  unicorn (5.0.1) bin/unicorn_rails:209:in `<top (required)>'
  /home/ubuntu/.rbenv/versions/2.2.3/bin/unicorn_rails:23:in `load'
  /home/ubuntu/.rbenv/versions/2.2.3/bin/unicorn_rails:23:in `<top (required)>'
  bundler (1.13.1) lib/bundler/cli/exec.rb:74:in `load'
  bundler (1.13.1) lib/bundler/cli/exec.rb:74:in `kernel_load'
  bundler (1.13.1) lib/bundler/cli/exec.rb:27:in `run'
  bundler (1.13.1) lib/bundler/cli.rb:332:in `exec'
  bundler (1.13.1) lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  bundler (1.13.1) lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  bundler (1.13.1) lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  bundler (1.13.1) lib/bundler/cli.rb:20:in `dispatch'
  bundler (1.13.1) lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  bundler (1.13.1) lib/bundler/cli.rb:11:in `start'
  bundler (1.13.1) exe/bundle:34:in `block in <top (required)>'
  bundler (1.13.1) lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
  bundler (1.13.1) exe/bundle:26:in `<top (required)>'
  /home/ubuntu/.rbenv/versions/2.2.3/bin/bundle:23:in `load'
  /home/ubuntu/.rbenv/versions/2.2.3/bin/bundle:23:in `<main>'

Any help would be appreciate it, also, if you need something else, just let me know and I will delivered as soon as possible.
Thank you and hope to hear from you soon.

**Comment by ryuzee** [comment]
@cusanelly "favicon.ico" is not a problem and this screen is intentional.

When you upload a deck, this screen is shown to wait for the completion of conversion.
Conversion from a deck to the resources that are used for this application is done by the batch procedure. See https://github.com/ryuzee/SlideHub#register-batch-procedure-to-cron-if-you-do-not-use-docker to register conversion process to your cron.

**Comment by cusanelly** [comment]
@ryuzee 
Got it, i registered the batch procedure and now looks beautiful.
Thank you very much for your support.
