### ISSUE TITLE
Add hosting slides on local support

### ISSUE THREAD

**Issue by imikay** [ryuzee/SlideHub#210]
It will be better if we could add support for hosting slides on local, by the way how much it cost if we host it on AWS? Thanks.

**Comment by ryuzee** [comment]
This application highly depends on Queue and Object Storage (NOT depending on EC2 or Virtual Machine). 
The cost of using Queue and Object Storage is usually quite low comparing to virtual machine. In my case, it only costs up to 5 USD per month including network transferring cost.

There are 2 reasons why the application is using these functionalities.
One is that, these functionalities provide redundancy and scalability.
Second is that, there's no need to spend time to maintain storage. 

When implementing local storage support, it's difficult to keep redundancy and scalability although we use NFS. Thus, from my view, the priority of this feature is not high for me.

**Comment by imikay** [comment]
Ok, thanks for the clarification. 👍
