### ISSUE TITLE
slideをアップロードすると、エラーが出る

### ISSUE THREAD

**Issue by Zaki-XL** [ryuzee/SlideHub#363]
エラーログを添付します

```
# Logfile created on 2018-06-21 14:18:09 +0900 by logger.rb/61378 
F, [2018-06-21T17:52:56.560283 #308] FATAL -- : 
F, [2018-06-21T17:52:56.560354 #308] FATAL -- : ActionView::Template::Error (missing region; use :region option or export region name to ENV['AWS_REGION']): 
F, [2018-06-21T17:52:56.560456 #308] FATAL -- : 27:
```

環境変数に
AWS_REGION=ap-northeast-1
を指定すると動作します

OSS_REGIONを参照していないような気がするのですが、こちらは仕様でしょうか？
ご確認よろしくお願いいたします

**Comment by ryuzee** [comment]
@Zaki-XL 

IAM Roleを使っているということでよろしいでしょうか？
であれば、ちょっと環境変数の取扱がよくなかったので、AWS_REGIONが必要な状態になってました。

`1.5.27`で修正してみましたので確認いただければと思います。

**Comment by Zaki-XL** [comment]
本件確認させていただきました
わたしの利用している状況をきちんとお伝えできてなくてすみません

ご対応ありがとうございました
