### ISSUE TITLE
カスタムコンテンツ設定について

### ISSUE THREAD

**Issue by Zaki-XL** [ryuzee/SlideHub#369]
管理者メニュー内のカスタムコンテンツ設定の使用方法を教えていただけますでしょうか

1.  「画面上部」「中央下部」はhtmlソースがそのままでるっぽい
1.  「右上部」は何が変化したのか不明
1.  「ヘッダー追加メニュー」の書式が不明
1. 「ページ一覧」で追加したページは「/pages/」+「パス」でアクセス出来る

という所まで判りました
ご教授の程よろしくおねがいします

**Comment by ryuzee** [comment]
@Zaki-XL 

1. そのとおりです
2. ユーザーのページの右上です
3. 以下のような書式になります。JSON形式でハッシュの配列です。ハッシュではlabelとurlを指定してください

```
[
{"label":"このサイトについて", "url":"/pages/about"},
{"label": "著作", "url": "https://www.amazon.co.jp/%E5%90%89%E7%BE%BD-%E9%BE%8D%E5%A4%AA%E9%83%8E/e/B01MYVNXWK/"},
{"label": "Attractor", "url": "https://www.attractor.co.jp/"}
]
```

4. そのとおりです
5. カスタムcssでは、cssの定義をそのまま書いてください

**Comment by Zaki-XL** [comment]
ご教授いただきありがとうございました！
動作確認させていただきました
