### ISSUE TITLE
Does not work on Azure.

### ISSUE THREAD

**Issue by ziqiaojin** [ryuzee/SlideHub#386]
Hello, thank you for creating this great project.

I am new to Azure and can't figure out the problem. the running app returns nothing or service unavailable.

I am trying on AWS now, this is more of a notice for you that the script is failing.

**Comment by ryuzee** [comment]
@ziqiaojin 

I cannot guess issues you encountered without any logs or explanations of your procedures...
For Azure, I think you can get a running application by following [this instruction](https://github.com/ryuzee/SlideHub/blob/master/docs/azure.md).

**Comment by ziqiaojin** [comment]
Thank you for the response. 
I was using the CUI script you provided to deploy on Azure.
For testing the only thing I changed was the password.

The running app take forever to load and yields 502 after.

**Comment by ryuzee** [comment]
@ziqiaojin 

Docker Hub was under maintenance on August 25. Thus if you tried to run app on that date, Azure might not be able to pull Docker image from Docker Hub. 
So please try followings.

1) Login to Azure Portal and access to App Services via left side menu 
2) Click `Restart` at the top in the overview page

if it does not resolve the problem, go to `Container settings` and you can confirm logs from the application.
