### ISSUE TITLE
embeded view not showing up

### ISSUE THREAD

**Issue by ziqiaojin** [ryuzee/SlideHub#389]
Hello, thanks for creating slide-hub
I deployed it on AWS and everything seems to work OK, except for the embedded view.
It only shows a broken file icon on the top left.(I am able to download the file I uploaded)
do you have any idea?
Thank you for your time.
EDIT: typo

**Comment by ryuzee** [comment]
@ziqiaojin I'd like to clarify the situation...

1. Does slide view (for example, https://slide.meguro.ryuzee.com/slides/74) work fine?
2. Do you mean the player is not working when you paste the script (like follows) into your web page?

```
<script src="https://slide.meguro.ryuzee.com/player/74"></script>
```

**Comment by ziqiaojin** [comment]
Thank you for your speedy reply,
The slide view is not working in any of the window, here is a screenshot:
https://imgur.com/a/Fk7MMme

**Comment by ryuzee** [comment]
@ziqiaojin 

Thanks for providing the information. 

1. Referring to the screenshot, you might not be able to show "/slides/index". If so, could you please access to "/slides/index" and provide me broken image link?
2. Also please provide me these information as follows?
 - AWS region you are using
 - Whether your S3 buckets are located in same AWS region as EC2 instance and other AWS resources
 - Whether you are using CDN (CloudFront) or not

**Comment by ziqiaojin** [comment]
1.Here is the URL for to the server I am testing with:
http://52.196.53.175:32774/slides/index
2.
- EC2: ap-northeast-1a
- S3: Asia Pacific(Tokyo) RDS: ap-northeast-1a
- no CDN

Thank you for you kind response.

**Comment by ryuzee** [comment]
I found that the image paths indicated like `http://slideshare-images/3ef80ea6b029deda7529b20bd06ee270/thumbnail.jpg`.
These are not the valid path. 
When I changed the path to `http://slideshare-images.s3-ap-northeast-1.amazonaws.com/3ef80ea6b029deda7529b20bd06ee270/thumbnail.jpg`, the image could be shown.

The following is the logic to create the image url.
if you set `OSS_USE_S3_STATIC_HOSTING`, the image bucket name will be a FQDN.
Thus I think you are now setting `OSS_USE_S3_STATIC_HOSTING=1` and the solution is to change the value from `1` to `0`.

```
def self.resource_endpoint
          return @config.cdn_base_url unless @config.cdn_base_url.blank?

          url = if @config.use_s3_static_hosting == '1'
                  "http://#{@config.image_bucket_name}"
                elsif @config.region == 'us-east-1'
                  "https://#{@config.image_bucket_name}.s3.amazonaws.com"
                else
                  "https://#{@config.image_bucket_name}.s3-#{@config.region}.amazonaws.com"
                end
          url
        end
```

Hope it helps.

**Comment by ziqiaojin** [comment]
Indeed it works fine now, and thank you for the detailed explanation.
cheers.
