### ISSUE TITLE
Yarn executable was not detected in the system.

### ISSUE THREAD

**Issue by ziqiaojin** [ryuzee/SlideHub#390]
I get this error when I run  docker-compose build.

Step 12/15 : RUN bash -l -c 'OSS_SECRET_KEY_BASE=dummy RAILS_ENV=production bundle exec rake assets:precompile'
 ---> Running in 393015a1d594
stdin: is not a tty
**Yarn executable was not detected in the system.**
Download Yarn at https://yarnpkg.com/en/docs/install
rake aborted!

I have tried install yarn by
https://yarnpkg.com/lang/en/docs/install/#debian-stable
and npm install yarn -g

Do you have any idea?

**Comment by ryuzee** [comment]
To build the application, you need to install “bower” and run “bower install” to retrieve required JavaScript libraries.
