### ISSUE TITLE
Does the buckets have to be public?

### ISSUE THREAD

**Issue by ziqiaojin** [ryuzee/SlideHub#422]
Hello, thank you for making this open-source and the supports :)
I have a question, are the buckets suppose to be public?
In my case they only work when they are public.

**Comment by ryuzee** [comment]
@ziqiaojin 

When running the app on AWS, the app requires 2 buckets.
One is for storing slide images and the other is for storing original decks.
The bucket for the first one (specified by OSS_IMAGE_BUCKET_NAME environment variable) must be public, and the latter one(specified by OSS_BUCKET_NAME environment variable) can be private.

**Comment by ziqiaojin** [comment]
Thank you for you kind response, 
I assume because unless there are a large number of slides and need to worry about crawlers crawling all the ppts, there are no reason to make the bucket private?

**Comment by ryuzee** [comment]
@ziqiaojin 

If you do not need to protect your original decks from downloading by anonymous, you do not need to make the bucket private.
