### ISSUE TITLE
Isn't implement password reset, yet?

### ISSUE THREAD

**Issue by cimadai** [ryuzee/SlideHub#58]
I tried password reset function. Then password reset link sent by SlideHub is not found action.

<img width="463" alt="2016-03-30 17 55 48" src="https://cloud.githubusercontent.com/assets/121499/14136981/97c06942-f6a0-11e5-8002-de4e6be2801e.png">

<img width="652" alt="2016-03-30 17 46 23" src="https://cloud.githubusercontent.com/assets/121499/14136880/25ab0ec0-f6a0-11e5-9c32-b807b707a8dc.png">

**Comment by ryuzee** [comment]
@cimadai 

In my environment, password reset form can be found as follows.

![image](https://cloud.githubusercontent.com/assets/272013/14159944/094fc616-f714-11e5-9680-8197082c6d31.png)

It's reasonable to confirm several points as follows.

## What rails environment (development, production, test) do you use?

- If development mode is on, error screen must be include detailed information (Thus, I suppose, you did not use development mode)
- If production mode is on, error screen contains the message like "The page you were looking for doesn't exist".
- From these 2 points, I think this error screen is not coming from SlideHub application.

## Confirming your server environment

- Are you running the app on your computer? Is this app listening on 3000/tcp?
 - I wonder you are running the app on other environment and also you are running some other ruby app on your computer. 
-  if you are running the app on other host, you must specify ENV['OSS_PRODUCTION_HOST'] for the hyperlink when production mode is on. Or if you run the app on localhost not with 3000 port, you need to set specific port number in config/environments/development.rb. You can find `config.action_mailer.default_url_options = { host: 'localhost:3000' }` and change 3000 to other port number.

**Comment by cimadai** [comment]
@ryuzee 

Thank you for your reply.

I'm sorry, after I post that issue I found mistake in my URL.

I use two docker environment: production and my local.

First, I sent a password reset mail in my local env, 
but my OSS_PRODUCTION_HOST and OSS_ROOT_URL still bound for production env.
So the URL in SlideHub sent mail is production env URL.

It worked properly, thank you!
