### ISSUE TITLE
Kvm: Bundle install within docker containers throws Bundler::HTTPError Could not fetch specs from http://rubygems.org/ http://rubygems.org/

### ISSUE THREAD

**Issue by nemesis1346** [ryuzee/SlideHub#670]
Hi everyone. I was trying to install this app in a development environment with docker and AWS. In my local machine it worked perfectly. Although I tried to run it in a kvm running Ubuntu 18.04 and had a problem when running docker-compose build which calls to dockerfile_dev file. The script goes through until it reaches: "RUN /bin/bash -lc bundle install"
The output is similar to this issue:
https://github.com/moby/moby/issues/7539

Although the exact log is the following:
.........
Step 19/30 : RUN /bin/bash -lc bundle install
 ---> Running in 153dcb674de3
mesg: ttyname failed: Inappropriate ioctl for device
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/^CERROR: Aborting.

nobleprog@mmaigua-xcbx:~/Documents/seoslidepresenter/script$ ping google.com
PING google.com (216.58.193.78) 56(84) bytes of data.
64 bytes from sea15s07-in-f14.1e100.net (216.58.193.78): icmp_seq=1 ttl=56 time=9.59 ms
64 bytes from sea15s07-in-f14.1e100.net (216.58.193.78): icmp_seq=2 ttl=56 time=4.75 ms
64 bytes from sea15s07-in-f14.1e100.net (216.58.193.78): icmp_seq=3 ttl=56 time=4.78 ms
64 bytes from sea15s07-in-f14.1e100.net (216.58.193.78): icmp_seq=4 ttl=56 time=12.2 ms
^C
--- google.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms

Can someone help me? These are the dependencies I have in my KVM:
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
Gem version: 3.0.3
Bundle version: 1.17.2
Ruby version: 2.6.5p114
Docker version: 
docker-compose version: 1.14.0
docker version: 18.09.7

**Comment by ryuzee** [comment]
@nemesis1346 

It might be networking issue, not the application issue.

* Are you using http(s) proxy? If so, you need to set `http_proxy` environment variable.
* Check if `outbound` policy of AWS security group permits https traffic to internet.

**Comment by nemesis1346** [comment]
@ryuzee Its not the policy of AWS. I ran in my local machine and everything worked. The problem is when I am trying to docker-compose binaries in an empty kvm. How could I know if I am using a proxy or not? Oh something additional is that WITHIN THE KVM, if I run bundle install locally it works(not within docker containers).

**Comment by ryuzee** [comment]
My understanding of your situation is as follows. Is it right?
- The app works fine on your computer
- The app does not work with Ubuntu 18 + kvm on AWS 

If so, you need to investigate the differences in terms of infrastructure environment.
The differences are kvm and AWS.

In any way, virtualization (docker) on virtualization (kvm) needs knowledge, and I think you do not need to use kvm to run the app.

I'm sorry but the issue has nothing to do with the application itself...
