### ISSUE TITLE
docker image pull and run application in docker container DIFFERENT PORT. 

### ISSUE THREAD

**Issue by nemesis1346** [ryuzee/SlideHub#671]
I everyone. What I want to do is to pull the docker image(ryuzee/slidehub) and run it in my local machine in a local host port WITHOUT having to rebuild it. Just pull it and run it.
My  knowledge of docker is limited but what I tried to do is the following based on https://docs.docker.com/network/network-tutorial-host/ for hosting the app locally:

docker pull ryuzee/slidehub:latest
 
docker images:
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
ryuzee/slidehub         latest              9960d22210d8        3 weeks ago         2.56GB

 sudo docker run --rm -d --network host --name slidehub_test 9960d22210d8

runs correctly, but doesnt have any port I can go to in my browser:

docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                     PORTS                                            NAMES
d96a2b9b2dc8        9960d22210d8            "/usr/bin/supervisor…"   2 hours ago         Up 2 hours                                                                  slidehub_test4

Then I tried to setup an specific port:
sudo docker run --rm -d -p 4343:80 --network host --name slidehub_test4 9960d22210d8

docker ps-a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                     PORTS                                            NAMES
d96a2b9b2dc8        9960d22210d8            "/usr/bin/supervisor…"   2 hours ago         Up 2 hours                                                                  slidehub_test4

nothing yet
maybe the image has an specific port or some special configuration?
Or am I missing something for make it run? 
Can someone help me please, I would really appreciate it? These are the dependencies I have in my KVM:

Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic
Gem version: 3.0.3
Bundle version: 1.17.2
Ruby version: 2.6.5p114
Docker version:
docker-compose version: 1.14.0
docker version: 18.09.7

**Comment by ryuzee** [comment]
@nemesis1346 

you are forwarding 4343 port to 80 port in docker. But the application uses 3000 port.
So port mapping settings may be `4343:3000`.

Also you need to add several environment variables to the command line.
See https://github.com/ryuzee/SlideHub/blob/master/README.md#run-application

Finally, the easiest way to run the app is to use docker-compose.

Hope it helps.
