### ISSUE TITLE
ERROR: Service 'app' failed to build: The command '/bin/sh -c bash -l -c 'OSS_SECRET_KEY_BASE=dummy RAILS_ENV=production bundle exec rake assets:precompile --trace'' returned a non-zero code: 1

### ISSUE THREAD

**Issue by nemesis1346** [ryuzee/SlideHub#672]
HI everyone I was trying to compile with docker-compose in an ubuntu 18.04 hardware virtual machine. When running:

`docker-compose build`

It picks the dockerfile_dev file to run the script and build the binaries of the docker container. Everything goes fines until it reaches this instruction in the dockerfile_dev:

`RUN bash -l -c 'OSS_SECRET_KEY_BASE=dummy RAILS_ENV=production bundle exec rake assets:precompile'`

I get this error:
** Execute assets:precompile
I, [2019-11-30T02:29:50.270580 #9]  INFO -- : Writing /opt/application/current/public/assets/admin-d7871c6baf4457cde714446c62b798bf928e012e4ba3e9ec2edfc60c87f184e1.js
I, [2019-11-30T02:29:50.271394 #9]  INFO -- : Writing /opt/application/current/public/assets/admin-d7871c6baf4457cde714446c62b798bf928e012e4ba3e9ec2edfc60c87f184e1.js.gz
rake aborted!
Sprockets::FileNotFound: couldn't find file 'admin_custom' with type 'text/css'
Checked in these paths: 
  /opt/application/current/app/assets/images
  /opt/application/current/app/assets/javascripts
  /opt/application/current/app/assets/stylesheets
  /opt/application/current/vendor/assets/bower_components
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/momentjs-rails-2.20.1/vendor/assets/javascripts
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootstrap3-datetimepicker-rails-4.17.47/vendor/assets/javascripts
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootstrap3-datetimepicker-rails-4.17.47/vendor/assets/stylesheets
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-bootstrap-views-0.0.11/app/assets/stylesheets
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actioncable-5.2.3/lib/assets/compiled
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activestorage-5.2.3/app/assets/javascripts
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-5.2.3/lib/assets/compiled
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/turbolinks-source-5.2.0/lib/assets/javascripts
  /opt/application/current/Rails/vendor/assets/fonts
  /opt/application/current/Rails/node_modules
  /opt/application/current/node_modules
/opt/application/current/app/assets/stylesheets/admin.css:16
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/resolve.rb:65:in `resolve!'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:399:in `resolve'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:178:in `each'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:178:in `process_directives'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:83:in `_call'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/directive_processor.rb:68:in `call'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/non-stupid-digest-assets-1.0.9/lib/non-stupid-digest-assets.rb:26:in `compile'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/root/.rbenv/versions/2.6.5/bin/rake:23:in `load'
/root/.rbenv/versions/2.6.5/bin/rake:23:in `<top (required)>'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/root/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
/root/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
ERROR: Service 'app' failed to build: The command '/bin/sh -c bash -l -c 'OSS_SECRET_KEY_BASE=dummy RAILS_ENV=production bundle exec rake assets:precompile --trace'' returned a non-zero code: 1

The instruction bundle exec rake assets:precompile fails and the docker container cannot build successfully. Thereafter when I am trying to connect to the port 3000 the app shows this message:

couldn't find file 'slidehub' with type 'text/css'
Checked in these paths: 
  /opt/application/current/app/assets/images
  /opt/application/current/app/assets/javascripts
  /opt/application/current/app/assets/stylesheets
  /opt/application/current/vendor/assets/bower_components
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/momentjs-rails-2.20.1/vendor/assets/javascripts
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootstrap3-datetimepicker-rails-4.17.47/vendor/assets/javascripts
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootstrap3-datetimepicker-rails-4.17.47/vendor/assets/stylesheets
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-bootstrap-views-0.0.11/app/assets/stylesheets
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actioncable-5.2.3/lib/assets/compiled
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activestorage-5.2.3/app/assets/javascripts
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionview-5.2.3/lib/assets/compiled
  /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/turbolinks-source-5.2.0/lib/assets/javascripts
  /opt/application/current/Rails/vendor/assets/fonts
  /opt/application/current/Rails/node_modules
  /opt/application/current/node_modules

Is there some problem with the installation of  my dependencies? What I did was the following:

`bower install`

`docker pull ryuzee/slidehub:latest`

`docker-compose build`

`docker-compose run app bash -l -c 'bundle exec rake db:create RAILS_ENV=development'`

Can someone give me feedback please? Am I lacking some step? Additionally the ENV variables seemed to be right.

I think is the problem but dont know how to solve it: 
`Sprockets::FileNotFound: couldn't find file 'admin_custom' with type 'text/css'
Checked in these paths: ....`

This is my environment:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
Docker version 18.09.7, build 2d0083d
docker-compose version 1.21.2, build a133471
Bundler version 1.17.2
Bower version 1.8.8

**Comment by ryuzee** [comment]
The error shows the lack of resources (images, css, javascripts). Thus you failed to retrieve these resources via bower.

In the SlideHub directory, run following commands

```
npm install -g bower
bower install
```
it requires nodejs.

**Comment by ryuzee** [comment]
bower works fine when you get the following output...

$ bower install       

```
bower                     invalid-meta for:/home/ryuzee/dev/tmp/test/SlideHub/bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower mousetrap#1.6.0           cached https://github.com/ccampbell/mousetrap.git#1.6.0
bower mousetrap#1.6.0         validate 1.6.0 against https://github.com/ccampbell/mousetrap.git#1.6.0
bower sticky-kit#1.1.2          cached https://github.com/leafo/sticky-kit.git#1.1.2
bower sticky-kit#1.1.2        validate 1.1.2 against https://github.com/leafo/sticky-kit.git#1.1.2
bower js-cookie#2.0.4           cached https://github.com/js-cookie/js-cookie.git#2.0.4
bower js-cookie#2.0.4         validate 2.0.4 against https://github.com/js-cookie/js-cookie.git#2.0.4
bower jquery.lazyload#1.9.7     cached https://github.com/tuupola/jquery_lazyload.git#1.9.7
bower jquery.lazyload#1.9.7   validate 1.9.7 against https://github.com/tuupola/jquery_lazyload.git#1.9.7
bower clipboard#1.7.1           cached https://github.com/zenorocha/clipboard.js.git#1.7.1
bower clipboard#1.7.1         validate 1.7.1 against https://github.com/zenorocha/clipboard.js.git#1.7.1
bower admin-lte#2.3.11          cached https://github.com/almasaeed2010/AdminLTE.git#2.3.11
bower admin-lte#2.3.11        validate 2.3.11 against https://github.com/almasaeed2010/AdminLTE.git#2.3.11
bower jquery.equalheights#1.5.2 cached https://github.com/mattbanks/jQuery.equalHeights.git#1.5.2
bower jquery.equalheights#1.5.2         validate 1.5.2 against https://github.com/mattbanks/jQuery.equalHeights.git#1.5.2
bower jquery#>=1.7                        cached https://github.com/jquery/jquery-dist.git#3.2.1
bower jquery#>=1.7                      validate 3.2.1 against https://github.com/jquery/jquery-dist.git#>=1.7
bower jquery#>=1.7                           new version for https://github.com/jquery/jquery-dist.git#>=1.7
bower jquery#>=1.7                       resolve https://github.com/jquery/jquery-dist.git#>=1.7
bower jquery#>=1.7                      download https://github.com/jquery/jquery-dist/archive/3.4.1.tar.gz
bower jquery#>=1.7                       extract archive.tar.gz
bower jquery#>=1.7                      resolved https://github.com/jquery/jquery-dist.git#3.4.1
bower jquery                    extra-resolution Unnecessary resolution: jquery#3.2.1
bower sticky-kit#1.1.2                   install sticky-kit#1.1.2
bower clipboard#1.7.1                    install clipboard#1.7.1
bower mousetrap#1.6.0                    install mousetrap#1.6.0
bower jquery.lazyload#1.9.7              install jquery.lazyload#1.9.7
bower js-cookie#2.0.4                    install js-cookie#2.0.4
bower jquery.equalheights#1.5.2          install jquery.equalheights#1.5.2
bower admin-lte#2.3.11                   install admin-lte#2.3.11
bower jquery#>=1.7                       install jquery#3.4.1
```

**Comment by nemesis1346** [comment]
Thanks @ryuzee I will look it up
