### ISSUE TITLE
スライドをアップロード後、スライドを「プライベート」に編集すると、「自分のスライド」に表示されなくなる

### ISSUE THREAD

**Issue by episodehand** [ryuzee/SlideHub#743]

**Comment by episodehand** [comment]
**問題内容**
- スライドをアップロード後、スライドを「プライベート」に編集すると、自分がアップロードしたスライドでも「自分のスライド」に表示されなくなる
**問い合わせ**
- こちら仕様でしょうか？仕様の場合、「プライベート」モードの意味をご教授頂けますでしょうか？

**Comment by ryuzee** [comment]
こちらですが、プライベートモードはあくまでURLを知らない人には見えないようにする、というモードです。本人は知ってて構わないので、少なくとも自分のスライドには表示するようにしました。また自分のスライドには変換中のものも表示するように変更しています。
