### ISSUE TITLE
スライドの埋め込みコードをiframeに変換することは可能でしょうか？

### ISSUE THREAD

**Issue by episodehand** [ryuzee/SlideHub#744]
**問題事象**
- スライドの埋め込みコードを取得する際、<script>になるため、Script実行を受け付けないサービスで利用できない

**問い合わせ**
- 上記について、設定変更などで変更することは可能でしょうか？

**Comment by ryuzee** [comment]
現状設定変更などでiframeを使った形の出力をすることはできません。ただ実装は難しくないです

**Comment by episodehand** [comment]
承知しました。
大変お手数ですが、上記実装頂くこと可能でしょうか？

**Comment by ryuzee** [comment]
- 仮実装、動作確認済
- 自動テストは影響箇所なしでテスト追加不要

**Comment by ryuzee** [comment]
スライドの画面のダイアログの表示の箇所で、Javascript版とiframe版のどちらかを選択できるようにした。
参考例

```
<iframe width=500 height=400 scrolling="no" frameborder="no" src="https://slide.meguro.ryuzee.com/html_player/101?prefix=jsab2146ef4ce9b8c583d36769852f0816"></iframe>
```

**Comment by episodehand** [comment]
@ryuzee 
最新版で確認いたしました。
この度は、お忙しいところご対応頂き誠にありがとうございました。
