### ISSUE TITLE
Can I use services that do not use Azure or AWS?

### ISSUE THREAD

**Issue by papalqi** [ryuzee/SlideHub#916]
For example, storage services like Tencent or Aliyun.

**Comment by ryuzee** [comment]
Unfortunately, at the moment, we only support Azure and AWS.

However, for cloud services like Tencent, they do offer storage and queue services, and I believe there are SDKs available for development. Therefore, it might be possible to support them if you write the code yourself.

**Comment by papalqi** [comment]
thanks
